### ISSUE TITLE
setup as typescript project

### ISSUE THREAD

**Issue by rbrtbrnschn** [codingthrone/coding-throne-bot#12]
Help wanted, I am not up to date on which configuration'd be best.

EDIT: Currently setting up a more broad, and well put together structure for the bot (in ts), as well as implementing the ts-discord library.

Please comment or leave a thumbs up for the comment below ⬇️ So i know which we will be using.  

> Okay heres the deal. Everyone here @nerdthatnoonelikes , @d-exclaimation on board with using https://discord-akairo.github.io/#/?
> 
> I definitely am!, (just thought @typeit/discord was more developed)
> Leave a thumbs up or comment if you do. Otherwise I will continue working with @typeit/discord, as I have just started with it.

**Comment by d-exclaimation** [comment]
The only way setting up typescript with discord.js I know is by using Discord.ts or @typeit/discord. The configuration is not that confusing but it's definitely different from regular discord.js, for example, it uses decorators and abstract classes as well. That's all I know 

https://github.com/OwenCalvin/discord.ts

**Comment by d-exclaimation** [comment]
Are we continuing with typescript-ing the bot?

I made a branch on my own fork and tried to implement typescript to the bot without changing functionalities

**Comment by raghavken** [comment]
I would be open to using typescript along with the discord-akairo bot framework.

https://discord-akairo.github.io/#/

**Comment by rbrtbrnschn** [comment]
> I would be open to using typescript along with the discord-akairo bot framework.
> 
> https://discord-akairo.github.io/#/

I looked at, and @typeit/discord. I think the latter looks more promising.

**Comment by rbrtbrnschn** [comment]
> Are we continuing with typescript-ing the bot?
> 
> I made a branch on my own fork and tried to implement typescript to the bot without changing functionalities

I forked it to see if theres any issues.
Let me try creating a bot with ts myslef, this or another version of a ts bot will definitely be pulled either today or this weekend. 👍🏼

**Comment by rbrtbrnschn** [comment]
> Are we continuing with typescript-ing the bot?
> 
> I made a branch on my own fork and tried to implement typescript to the bot without changing functionalities

also, there is a @command decorator to my knowledge, did not see you using that for the commands, was that intentional?

**Comment by d-exclaimation** [comment]
Yeah, because I was trying to preserve the way the original bot fetches commands dynamically.

Using @Command would have been a lot better, but It wasn't something I prioritize until I can get a working bot. Not to mention, I have to do a lot more things, if so, rather than just porting the original code to typescript

**Comment by d-exclaimation** [comment]
> I would be open to using typescript along with the discord-akairo bot framework.
> 
> https://discord-akairo.github.io/#/

I also like this as well. It seems a lot more developed than @typeit/discord

**Comment by rbrtbrnschn** [comment]
> > I would be open to using typescript along with the discord-akairo bot framework.
> > https://discord-akairo.github.io/#/
> 
> I also like this as well. It seems a lot more developed than @typeit/discord

rip, I would've said the exact opposite

**Comment by rbrtbrnschn** [comment]
> Yeah, because I was trying to preserve the way the original bot fetches commands dynamically.
> 
> Using @command would have been a lot better, but It wasn't something I prioritize until I can get a working bot. Not to mention, I have to do a lot more things, if so, rather than just porting the original code to typescript

i am currently working on  "do[ing] alot more thing, ..., rathen than just porting the original code"
I haven't implemented much of @typeit/discord anyways, besides the boilerplate and some listeners.

**Comment by rbrtbrnschn** [comment]
Okay heres the deal. Everyone here @nerdthatnoonelikes , @d-exclaimation on board with using https://discord-akairo.github.io/#/?

I definitely am!, (just thought @typeit/discord was more developed) 
Leave a thumbs up or comment if you do. Otherwise I will continue working with @typeit/discord, as I have just started with it.

**Comment by d-exclaimation** [comment]
Let's a poll or something, maybe some other people wouldn't even want Typescript. I personally think this decision should be made collectively so that contributing is much nicer

In addition, I want to try out discord-akario for myself first.

**Comment by rbrtbrnschn** [comment]
> Let's a poll or something, maybe some other people wouldn't even want Typescript. I personally think this decision should be made collectively so that contributing is much nicer
> 
> In addition, I want to try out discord-akario for myself first.

I have just reached out to the founders/admins and mods of the discord for the poll for either wrapper (typeit/akairo)

I will not be making a poll / asking others to open one about typescript or javascript, given the language similarities, given it's basically the same, simply supersetted. (with added compiler warnings, yadda, yadda, yadda)

**Comment by rbrtbrnschn** [comment]
on that topic I am currently working on some form of config module, it's insane how much typescript is helping here.

**Comment by rbrtbrnschn** [comment]
closed with #16
